use BdMovimento;
go
IF OBJECT_ID(N'dbo.PRODUTO', N'U') IS NOT NULL  
   DROP TABLE [dbo].[PRODUTO];  
GO
CREATE TABLE PRODUTO (
	COD_PRODUTO [CHAR](4) PRIMARY KEY NOT NULL,
	DES_PRODUTO [VARCHAR](30) NULL,
	STA_STATUS [CHAR](1)
)
GO
IF OBJECT_ID(N'dbo.PRODUTO_COSIF', N'U') IS NOT NULL  
   DROP TABLE [dbo].[PRODUTO_COSIF];  
GO
CREATE TABLE PRODUTO_COSIF(
 COD_PRODUTO [CHAR](4) NOT NULL,
 COD_COSIF [CHAR](11) NOT NULL,
 COD_CLASSIFICACAO [CHAR](6) NULL,
 STA_STATUS [CHAR](1),
 CONSTRAINT PK_PRODUTO_COSIF PRIMARY KEY ( COD_PRODUTO, COD_COSIF),
 CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
)
GO

IF OBJECT_ID(N'dbo.MOVIMENTO_MANUAL', N'U') IS NOT NULL  
   DROP TABLE [dbo].[MOVIMENTO_MANUAL];  
GO

CREATE TABLE MOVIMENTO_MANUAL(
DAT_MES [integer] NOT NULL,
DAT_ANO [integer] NOT NULL,
NUM_LANCAMENTO [INTEGER] NOT NULL,
COD_PRODUTO [CHAR](4) NOT NULL,
COD_COSIF [CHAR](11),
DES_DESCRICAO [VARCHAR](50) NOT NULL,
COD_USUARIO [VARCHAR](15) NOT NULL,
VAL_VALOR [DECIMAL](18,2) NOT NULL,
CONSTRAINT PK_MOVIMENTO_MANUAL PRIMARY KEY (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF) ,
CONSTRAINT FK_PRODUTO_COSIF_MOVTO FOREIGN KEY (COD_PRODUTO, COD_COSIF) REFERENCES PRODUTO_COSIF(COD_PRODUTO , COD_COSIF)
)
